# Generated by Django 4.0.5 on 2022-06-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_aprendizados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Assuntos',
        ),
    ]
